### ISSUE TITLE
MakieとSattelliteToolBoxのQuaternionが同時に使用できない？

### ISSUE THREAD

**Issue by UGHyodo** [yui-project/ACSim#24]
## エラーが現れる状況
`using Makie`をしてから、SattelliteToolBoxのQuaternionを使用しているファイルを`include`したとき  
順番が逆だと警告は出るがエラーにはならない。ただどんな動作をするか分からないので根本的に解決したい。
## エラー内容
`WARNING: both SatelliteToolbox and Makie export "Quaternion"; uses of it in module Main must be qualified
ERROR: LoadError: LoadError: LoadError: UndefVarError: Quaternion not defined`
## エラーの原因(予測)
Makieの構成パッケージである`AbstractPlots.jl`でQuaternionという名前の何かをエクスポートしている。  
`include("utilities/quaternions.jl")`という文があったので`utilities/quaternions.jl`を見てみると、なんとオリジナルのQuaternion型と計算関数の定義だった。  
それがSattelliteToolBoxが使用している`ReferenceFrameRotations.jl`で定義されているQuaternionと干渉しているらしかった。
## 対策(暫定)
どちらのQuaternionを使用するかを明示的に宣言できれば解決できる。そのような方法がないか調べてみる。

**Comment by UGHyodo** [comment]
issueたてました。とりあえず姿勢制御系の人をAssignしましたが、通知を飛ばすためです。

**Comment by ZetaCapricorni** [comment]
そもそもQuaternionsのクォータニオン使ってましたわ...コード修正します

**Comment by UGHyodo** [comment]
これ昨日ちょっと調べたんですけどどうも同じ名前の型は複数作れないっぽくて詰んだ感あります

**Comment by ZetaCapricorni** [comment]
makieとsatellitetoolboxのクォータニオン定義が違ったら詰みですねえ

ちなみにsatellitetoolboxは以下のよう
`"""
    Quaternion{T}
The definition of the quaternion. It has four values of type `T`. The
quaternion representation is:
    q0 + q1.i + q2.j + q3.k
"""
struct Quaternion{T}
    q0::T
    q1::T
    q2::T
    q3::T
end`
